### ISSUE TITLE
Alt-Shift-l to read aloud the translation

### ISSUE THREAD

**Issue by Yekutiel** [alex91ivanov/firefox_shortcuts_for_gt#1]
I hope you will add the following feature:

**Alt-Shift-l to read aloud the translation.** (As you of course know, currently Alt-l reads aloud the text that was copied).

See, I speak English but am studying French. However, I like to brush up on my Spanish. Therefore, when I translate French text I normally have Google Translate translate it into Spanish, not English. Although I normally understand the written Spanish, because I am a non-native speaker of Spanish I like to hear the Spanish spoken aloud in Google Translate as well as the French.

Thank you for this simple yet remarkably useful add-on. I am surprised that Google Translate does not offer this feature.

**Comment by alex91ivanov** [comment]
hi
as you can see i was a little bit busy anyway if you are are still alive and interested i've updated my extension and you are free to check it out
there are extensions for both chrome and firefox from other guy which keep me satisfied:

https://addons.mozilla.org/en-US/firefox/addon/kbsc-for-google-translate/
https://chrome.google.com/webstore/detail/keyboard-shortcuts-for-go/akjhnbnjanndggbcegmdggfjjclohjpo

but after recent Google Translate design change it's not working for firefox anymore so here is my two cents:
https://addons.mozilla.org/en-US/firefox/addon/shortcuts-for-google-translate/

you can change default shortcuts in about:addons => Preferences
hope it helps
